services:
  app:
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m  # Optimize memory usage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/actuator/health"]
      interval: 10s  # Check more frequently
      timeout: 5s    # Faster timeout
      retries: 6     # More retries with shorter intervals
      start_period: 20s  # Reduced startup time

  # Cypress testing service (optimized for CI)
  cypress:
    image: cypress/included:13.6.4
    depends_on:
      app:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://app:8083
      - CYPRESS_video=false  # Disable video in CI for speed
      - CYPRESS_screenshotOnRunFailure=true
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
      - ./cypress/screenshots:/e2e/cypress/screenshots
      - ./cypress/videos:/e2e/cypress/videos
    entrypoint: [""]
    command: 
      - sh
      - -c
      - |
        echo 'Waiting for application to be ready...'
        until wget --quiet --tries=1 --spider http://app:8083/actuator/health; do
          echo 'Application not ready, waiting...'
          sleep 5
        done
        echo 'Application is ready, running Cypress tests...'
        cypress run --config baseUrl=http://app:8083
    networks:
      - default

networks:
  default:
    driver: bridge
